title: |
  "'What did the Robot do in my Absence?'\n
  Video Foundation Models to Enhance Intermittent Supervision"

description: We're excited to share our ongoing research.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
