title: |
  'What did the Robot do in my Absence?'
  Video Foundation Models to Enhance Intermittent Supervision

description: The project page for the research paper.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
